clc;
clear all;
close all;
x=0:.2:2;
y=2*exp(-2*x);
row=2;
col=1;
figure(1);
subplot(row,col,1);
stem(x,y);
grid on;
title('subplot-1:discrete plot:y=2e^-2x');
xlabel('x');
ylabel('y');
subplot(row,col,2);
plot(x,y);
grid on;
title('subplot-2:continious plot:y=2e^-2x');
xlabel('t(in sec)');
ylabel('y');