clc;
clear all;
close all;
t=-10:1:10;
u=zeros(size(t));
u(t>=0)=1;
figure(1);
subplot(2,1,1);
plot(t,u);
grid on;
xlabel('time(t)');
ylabel('u(t)');
title('continious unit step function');
axis([-10 10 -.5 1.5]);
subplot(2,1,2);
stem(t,u);
grid on;
xlabel('time(n)');
ylabel('u(n)');
title('discrete unit step function');
axis([-10 10 -.5 1.5]);